"""Azure DevOps (ADO) work-item export.

Creates a `Bug` work item via the ADO REST API using a PAT. Repro steps are
rendered as HTML into `Microsoft.VSTS.TCM.ReproSteps` (the field the ADO Bug
form displays as "Repro Steps"). Connection settings resolve in order:
export options → org settings → environment (VIDREPRO_ADO_*).
"""
import html
from urllib.parse import quote

import requests
from fastapi import HTTPException

from vidrepro.config import get_settings
from vidrepro.contracts.report import ReportBody

API_VERSION = "7.1"


def _ts(ms: int) -> str:
    s = ms // 1000
    return f"{s // 60}:{s % 60:02d}"


def render_repro_html(body: ReportBody) -> str:
    e = html.escape
    parts: list[str] = []
    if body.summary:
        parts.append(f"<p>{e(body.summary)}</p>")
    if body.preconditions:
        parts.append("<p><b>Preconditions</b></p><ul>")
        parts += [f"<li>{e(p.text)}</li>" for p in body.preconditions]
        parts.append("</ul>")
    parts.append("<p><b>Steps to Reproduce</b></p><ol>")
    for step in body.steps:
        span = f" [{_ts(step.evidence[0].t_start_ms)}]" if step.evidence else ""
        warn = (f"<br/><i>Note: {e(step.uncertainty_note)}</i>"
                if step.uncertainty_note else "")
        parts.append(f"<li>{e(step.text)}{span}{warn}</li>")
    parts.append("</ol>")
    parts.append(f"<p><b>Observed Result</b><br/>{e(body.observed_result.text)}</p>")
    if body.expected_result:
        parts.append(
            f"<p><b>Expected Result</b><br/>{e(body.expected_result.text)} "
            f"<i>(basis: {body.expected_result.basis})</i></p>"
        )
    else:
        parts.append("<p><b>Expected Result</b><br/><i>Not inferable from the "
                     "recording; reviewer should confirm.</i></p>")
    env = body.environment
    env_bits = [f"{k}: {e(v)}" for k, v in
                [("OS", env.os), ("Browser", env.browser), ("App", env.app),
                 ("Device", env.device_class), ("Resolution", env.resolution)]
                if v and v != "unknown"]
    if env_bits:
        parts.append("<p><b>Environment (inferred from video)</b><br/>" + "<br/>".join(env_bits) + "</p>")
    if body.ambiguity_notes:
        parts.append("<p><b>Ambiguities</b></p><ul>")
        parts += [f"<li>{e(n)}</li>" for n in body.ambiguity_notes]
        parts.append("</ul>")
    parts.append(f"<p><i>Generated by VidRepro. Overall confidence "
                 f"{body.overall_confidence:.2f}</i></p>")
    return "".join(parts)


def severity_for(bug_type: str) -> str:
    return {"crash": "1 - Critical", "functional": "2 - High"}.get(bug_type, "3 - Medium")


def create_ado_bug(body: ReportBody, org_settings: dict, options: dict) -> dict:
    s = get_settings()
    ado_org = options.get("ado_org") or org_settings.get("ado_org") or s.ado_org
    ado_project = options.get("ado_project") or org_settings.get("ado_project") or s.ado_project
    pat = options.get("ado_pat") or org_settings.get("ado_pat") or s.ado_pat
    if not (ado_org and ado_project and pat):
        raise HTTPException(
            400,
            "Azure DevOps is not configured. Set ado_org/ado_project/ado_pat in org "
            "settings or VIDREPRO_ADO_* environment variables.",
        )

    severity = severity_for(body.bug_type)
    tags = f"vidrepro; {body.bug_type}"
    patch = [
        {"op": "add", "path": "/fields/System.Title", "value": body.title[:255]},
        {"op": "add", "path": "/fields/Microsoft.VSTS.TCM.ReproSteps", "value": render_repro_html(body)},
        {"op": "add", "path": "/fields/Microsoft.VSTS.Common.Severity", "value": severity},
        {"op": "add", "path": "/fields/System.Tags", "value": tags},
    ]
    if options.get("area_path"):
        patch.append({"op": "add", "path": "/fields/System.AreaPath", "value": options["area_path"]})
    if options.get("iteration_path"):
        patch.append({"op": "add", "path": "/fields/System.IterationPath", "value": options["iteration_path"]})

    url = (f"https://dev.azure.com/{quote(ado_org)}/{quote(ado_project)}"
           f"/_apis/wit/workitems/$Bug?api-version={API_VERSION}")
    resp = requests.post(
        url,
        json=patch,
        headers={"Content-Type": "application/json-patch+json"},
        auth=("", pat),  # ADO PATs use basic auth with empty username
        timeout=30,
    )
    if resp.status_code >= 300:
        raise HTTPException(502, f"Azure DevOps rejected the work item ({resp.status_code}): "
                                 f"{resp.text[:500]}")
    data = resp.json()
    web_url = (data.get("_links", {}).get("html", {}) or {}).get("href") or (
        f"https://dev.azure.com/{quote(ado_org)}/{quote(ado_project)}/_workitems/edit/{data['id']}"
    )
    return {"id": data["id"], "url": web_url}
