"""Markdown export. Deliberately sparse markup: no italics/emphasis wrappers,
no symbol glyphs — those read as literal underscores and mojibake the moment
the text lands in a plain textarea, an email, or a ticket field. Timestamps
are plain [m:ss]; only genuinely low-confidence steps get a textual flag."""
from vidrepro.contracts.report import ReportBody


def _ts(ms: int) -> str:
    s = ms // 1000
    return f"{s // 60}:{s % 60:02d}"


def render_markdown(body: ReportBody) -> str:
    lines: list[str] = [f"# {body.title}", ""]
    if body.summary:
        lines += [body.summary, ""]
    lines += [f"Bug type: {body.bug_type} | Overall confidence: {body.overall_confidence:.2f}", ""]

    if body.preconditions:
        lines += ["## Preconditions", ""]
        for p in body.preconditions:
            lines.append(f"- {p.text}")
        lines.append("")

    lines += ["## Steps to Reproduce", ""]
    for step in body.steps:
        span = f"[{_ts(step.evidence[0].t_start_ms)}] " if step.evidence else ""
        flag = " (low confidence)" if step.confidence < 0.6 else ""
        lines.append(f"{step.index}. {span}{step.text}{flag}")
        if step.uncertainty_note:
            lines.append(f"   - Note: {step.uncertainty_note}")
    lines.append("")

    lines += ["## Observed Result", "", body.observed_result.text]
    if body.observed_result.evidence:
        lines.append(f"(evidence at {_ts(body.observed_result.evidence[0].t_start_ms)})")
    lines.append("")

    lines += ["## Expected Result", ""]
    if body.expected_result:
        lines += [body.expected_result.text,
                  f"(basis: {body.expected_result.basis}, "
                  f"confidence {body.expected_result.confidence:.2f})"]
    else:
        lines += ["Not stated - the recording does not contain enough evidence "
                  "to infer expected behavior."]
    lines.append("")

    env = body.environment
    env_bits = [f"{k}: {v}" for k, v in
                [("OS", env.os), ("Browser", env.browser), ("App", env.app),
                 ("Device", env.device_class), ("Resolution", env.resolution),
                 ("Theme", env.theme)] if v and v != "unknown"]
    if env_bits:
        lines += ["## Environment (inferred from video)", "", "- " + "\n- ".join(env_bits), ""]

    if body.bug_manifestation:
        lines += ["## Bug Manifestation", "",
                  f"At {_ts(body.bug_manifestation.t_ms)} "
                  f"(confidence {body.bug_manifestation.confidence:.2f})", ""]

    if body.ambiguity_notes:
        lines += ["## Ambiguities", ""] + [f"- {n}" for n in body.ambiguity_notes] + [""]

    if body.omitted_activity:
        lines += ["## Omitted Activity", ""] + [
            f"- {_ts(o.t_start_ms)}-{_ts(o.t_end_ms)}: {o.reason}" for o in body.omitted_activity
        ] + [""]

    lines += ["---", "Generated by VidRepro from a screen recording. "
              "Steps are evidence-grounded; confidence is per-step."]
    return "\n".join(lines)
