"""Plain-text export: pure ASCII, no markup of any kind. Safe to paste into
any ticket field, email, chat, or terminal. This is the format for people who
just want the repro steps as readable sentences."""
from vidrepro.contracts.report import ReportBody


def _ts(ms: int) -> str:
    s = ms // 1000
    return f"{s // 60}:{s % 60:02d}"


def _rule(title: str) -> list[str]:
    return [title, "-" * len(title)]


def render_text(body: ReportBody) -> str:
    lines: list[str] = ["BUG REPORT", "=" * 10, ""]
    lines.append(f"Title:      {body.title}")
    lines.append(f"Bug type:   {body.bug_type}")
    lines.append(f"Confidence: {body.overall_confidence:.2f} (overall)")
    if body.summary:
        lines += ["", body.summary]
    lines.append("")

    if body.preconditions:
        lines += _rule("PRECONDITIONS")
        for p in body.preconditions:
            lines.append(f"- {p.text}")
        lines.append("")

    lines += _rule("STEPS TO REPRODUCE")
    for step in body.steps:
        span = f" [{_ts(step.evidence[0].t_start_ms)}]" if step.evidence else ""
        flag = " (low confidence)" if step.confidence < 0.6 else ""
        lines.append(f"{step.index:>2}. {step.text}{flag}{span}")
        if step.uncertainty_note:
            lines.append(f"    Note: {step.uncertainty_note}")
    lines.append("")

    lines += _rule("OBSERVED RESULT")
    lines.append(body.observed_result.text)
    if body.observed_result.evidence:
        lines.append(f"(evidence at {_ts(body.observed_result.evidence[0].t_start_ms)})")
    lines.append("")

    lines += _rule("EXPECTED RESULT")
    if body.expected_result:
        lines.append(body.expected_result.text)
        lines.append(f"(basis: {body.expected_result.basis}, "
                     f"confidence {body.expected_result.confidence:.2f})")
    else:
        lines.append("Not stated - the recording does not contain enough "
                     "evidence to infer expected behavior.")
    lines.append("")

    env = body.environment
    env_bits = [f"{k}: {v}" for k, v in
                [("OS", env.os), ("Browser", env.browser), ("App", env.app),
                 ("Device", env.device_class), ("Resolution", env.resolution),
                 ("Theme", env.theme)] if v and v != "unknown"]
    if env_bits:
        lines += _rule("ENVIRONMENT (inferred from video)")
        lines += [f"- {b}" for b in env_bits]
        lines.append("")

    if body.bug_manifestation:
        lines += _rule("BUG MANIFESTATION")
        lines.append(f"At {_ts(body.bug_manifestation.t_ms)} "
                     f"(confidence {body.bug_manifestation.confidence:.2f})")
        lines.append("")

    if body.ambiguity_notes:
        lines += _rule("AMBIGUITIES")
        lines += [f"- {n}" for n in body.ambiguity_notes]
        lines.append("")

    if body.omitted_activity:
        lines += _rule("OMITTED ACTIVITY")
        lines += [f"- {_ts(o.t_start_ms)}-{_ts(o.t_end_ms)}: {o.reason}"
                  for o in body.omitted_activity]
        lines.append("")

    lines.append("Generated by VidRepro from a screen recording.")
    return "\n".join(lines)
